### PR TITLE
Unified OSX/Windows/Linux build system and CI

### PR DESCRIPTION
**Pull request by scyptnex**
Attempt 2 of the unified build system

* added support for Appveyor CI on windows
* extended support for OSX builds on Travis
* Merged and extended the CMake build system for all 3 major platforms
* Converted the testing framework to use the cross-platform CTest
* fixed a bug on OSX where a box-size description like 'x7' is being interpreted as hexadecimal 7
* modified testrunner.sh to take the executable binary and configuration files as arguments

### CODE REVIEW

**Comment by scyptnex** [comment]
The above error is caused by use of non posix-compliant sed commands.

Can either make some changes to the testrunner.sh or re-adopt the python version

**Comment by tsjensen** [comment]
Thank you for your patience. I really appreciate your contribution.
I finally got around to looking at this more closely, and ended up with a few (hopefully minor) questions and comments. I understand the Appveyor and Travis changes, and the `x7` OSX fix. Great work!
CMake is also cool, although I must admit I did not get it to run the tests from CLion, but that's probably my fault. ;-)

1. The CMake build should be optional, in addition to the regular GNU make build. The regular GNU make build should continue to function as documented, although we can of course change the documentation. I understand that's how you designed it, so that's great. However, I am unable to run the cmake build in MinGW. It builds the executable, but fails to run the tests:
    ```
    CMake Error at CMakeLists.txt:17 (add_test):
      Error evaluating generator expression:
    
        $<TARGET_FILE:>
    
      Expression syntax not recognized.
    Call Stack (most recent call first):
      CMakeLists.txt:34 (BOXES_TEST)
    ```
1. Would you please also update the [documentation](http://boxes.thomasjensen.com/testing.html) on running the tests to fit the new mechanism? Especially about how to run the entire test suite; I tried
    ```
    $ make test
    cd test; ./testrunner.sh -suite
    Usage: testrunner.sh <executable> <configFile> <testCaseFile>
           Returns 0 for success, else non-zero
    make: *** [test] Error 2
    ```
1. The change to *.gitignore* seems to add a redundancy, as `bin` is now contained twice.

1. The Travis CI is currently failing, which may be because we just don't support clang? We would need a green Travis Build, also.

1. Would you please squash the last three commits into one? I can offer to do this on my side, but frankly I don't know if this will affect the author information.

That was it! Sorry about the long list of comments, but these were many topics in one PR. Thanks again and let me know if anything was unclear or if you disagree.

**Comment by scyptnex** [comment]
This is all doable, just need to confirm a few things:
1) **preserving gnu-make**, CMake of course creates its own Makefiles, which override the existing Makefiles (if you do an in-source build), this cant really be avoided, we just need to be mindful that it is happening.
2) **running tests** the above error seems to be caused by the `${BOXES_EXE}` target being undefined, it is defined in `boxes/CMakeLists.txt`, and then used in `boxes/tests/CMakeLists.txt`, the correct behaviour is to configure only the top-level cmake file, then call "make check" from the top level directory (if you configure or call from the tests directory itself, that variable will be undefined)
3) **Travis build** unfortunately travis breaks because the `sed` command is not standardised between OSX and Linux.Easiest solutions are to modify the `testrunner.sh` to not use `sed`, or to re-implement the python-based suite.

When i've got your thoughts on the above 3, i can proceed with documentation, cleaning the .gitignore and commit squashing

**Comment by tsjensen** [comment]
1. **GNU make** - Overwriting these files is fine. In the documentation, we should warn people that this happens, so they'll have to checkout again from git if they want to switch build systems.
1. **tests** - Ok, but it must be possible to execute the entire test suite with both build systems. Maybe the `-suite` parameter to the script was good for something after all :smirk: 
1. **sed** - Well I hope that the `sed` commands on OSX are not *that* different, and an implementation can be found that works in both cases. If not, again that's fine as long as it's documented. We need to have OSX as a platform to *run* boxes, but we did not promise that boxes can be *developed* on OSX. Python is really not possible, except maybe as an option, because it would introduce a major dependency where I personally lack the skill to support it. Also, boxes benefits from its very small dependency tree ([example](https://github.com/Homebrew/legacy-homebrew/pull/34292)), which is nice.

**Comment by tsjensen** [comment]
Superseded by #35

**Pull request closed without merging**
