### PR TITLE
Added empty align box

### PR DESCRIPTION
**Pull request by Davidy22**
Used a full width space character to cheat the check. Potential resolution to #88.

### CODE REVIEW

**Comment by Davidy22** [comment]
Hrm. just noticed this alignment method mangles asymmetric inputs when centering.

**Comment by tsjensen** [comment]
According to the [docs](https://boxes.thomasjensen.com/boxes-man-1.html#OPTIONS), `-ac` is short for `-a hcvcjc`, the `jc` part of which means:

> jx - justification of lines within the input text block. Possible values for x are `l` (ell, for left justification), `c` (center), or `r` (right). This does not affect the alignment of the input text block itself within the box. Use the h and v arguments for input text block positioning.

In the [FAQ](https://boxes.thomasjensen.com/faq.html#q7), I explained it like this:

> Note that we `-a hc` instead of just `-ac`, because we want to align the whole block of text, not individual lines.

**Comment by tsjensen** [comment]
The greater problem is that the config file is in ASCII format, so the unicode space character is a forbidden character atm. 😢

**Comment by tsjensen** [comment]
But it seems you can still use this trick on unicode-enabled terminals using the `-c` option (the argument to `-c` is your full-width space!):

    echo -e foo\\ncentered | boxes -d parchment -p h5 | out/boxes -s $(tput cols) -c "　" -a hc -i none

This works for me.

**Pull request closed without merging**
