### PR TITLE
new designs added: "fence" and "important" 1,2,3

### PR DESCRIPTION
**Pull request by bdimych**

### CODE REVIEW

**Comment by tsjensen** [comment]
Thanks! We have started to list both the designer of the original ASCII art (`designer`) and the person who transformed the design into *boxes* code (`author`). So if you know the original designer, or if you are that person yourself, please add this information to the file, too.

**Comment by bdimych** [comment]
Hello, ok, done - I added the designer field

**Comment by tsjensen** [comment]
Thank you for your contribution!

**Comment by tsjensen** [comment]
BTW, you may want to add `bdimych@narod.ru` to the [list of email addresses](https://github.com/settings/emails) in your GitHub account. That would enable GitHub to attribute your commit to you.

**Comment by bdimych** [comment]
ok, thanks, but recently I decided to start moving from narod.ru and I'm
trying to use it as little as possible

---
With Best Regards
Dmitry Bolshakov
bdimych@gmail.com

**Pull request merged**
