### PR TITLE
~~NEW BOX: "Scroll-AKN"~~ (move to other commit)

### PR DESCRIPTION
**Pull request by tajmone**
Added new box design "Scroll-AKN" to boxes-config file. (fully tested)

NOTE: Scroll design was found on the internet, it appears all over the place, most often with an "akn" signature on it. Seems an old design, from the BBS era possibly.

I doubt any copyright applies to it. But to be fair toward the original author, I mention in the box sample "akn" as the author, and myself as merely the implementor. The author tag though has my full name and email (taking responsibility for it!).

Hope this is the correct way to procede.

### CODE REVIEW

**Comment by tsjensen** [comment]
Thank you for another cool box design! Can you rename `keywords` to `tags` on this one, also? Thanks!

**Comment by tajmone** [comment]
Done!

**Comment by tsjensen** [comment]
Great - last but not least, please squash both commits into one. I'm ready to merge. Thank you!

**Comment by tajmone** [comment]
Sorry for the delay, but I am not very practical on some Git issues, special with GitHub 4 Windows...
It looks ok, though. Could you just confirm?

**Comment by tajmone** [comment]
I've added the Ankh design into the Twisted push request, making it a single commit!

**Comment by tsjensen** [comment]
Merged. Many thanks!

**Pull request merged**
