### PR TITLE
New box designs: Twisted + Scroll-AKN

### PR DESCRIPTION
**Pull request by tajmone**
Added a new boxes frame design: "Twisted-Geometries". Tested, works
well.

### CODE REVIEW

**Comment by tsjensen** [comment]
Thanks for this cool new design!

May I request two small changes:
- It should have a shorter name, so people can more easily select it from the command line, e.g. just `geom` or `twisted`.
- Can you rename the `keywords` keyword to `tags` as per #23.

I don't want to cause you too much extra work. If it's too much hassle for you, I can do it for you.

**Comment by tajmone** [comment]
Ok, done!

**Comment by tsjensen** [comment]
Great - could you please also squash these commits into one? Thank you!

**Comment by tajmone** [comment]
RIGHT, I've added into this commit also the other design, I think this is what you meant!

**Comment by tsjensen** [comment]
Oops, no, we want 1 commit per design, like you did in your other pull request. Sorry if that was not entirely clear.
I already merged the other PR, so you can just remove the 'scroll-akn' part from this one. Thanks!

**Comment by tajmone** [comment]
Sorry for the mess. Point is:

1. I've never been on the receiving side of pull requests, so I really don't understand much what your costrains are, ecc.
2. It's been quite a while I haven't used Git, and I always find it over-complicated and troublesomely documented (masochists style terminology—one wonders if it was meant to deterr people from using it). "Squash", "Pull", "Push", "Rebase", "Cherry picking" ... what a lingo! really, theresn't much in these words that creates imagery of associations that help memorizing them, on the contrary!

So, to avoid further damage. What am I supposed to? I see no options to withdraw this pull request. All I could do is delete the AKN design, but doesn't make much sense, isn't easy to ignore it, delete it?

**Comment by tsjensen** [comment]
Don't worry, Git can be tough in the first couple years using it. ;-)
I would recommend this procedure:
- Check out your `tajmone:Twisted-Geometries` branch.
- Change the boxes-config file by removing the scroll-akn design. This leaves only the *twisted* design which is the object of this pull request.
- Commit this change locally

Now you have 2 commits, which must be squashed:

- `git log` and find the commit hash of the commit just prior to the new commits.
- `git rebase -i <thisHash>`, then follow on-screen instructions carefully. You end up with the branch containing just one new commit
- `git push --force`

Hope this helps! If all else fails, I can do it for you, but then you may not show up in the contributors list with your new design; so let's give it one more try.

**Comment by tajmone** [comment]
Done!
I'll have to lookup the Git documentation though. I don't understand the "meaning" of all this, but I guess it has to do with keeping a good historical record of who did what.
Even though, from what I gather, rebasing and forced pushing is in itself a procedure which might jeopardize this very intention—in large projects, where someone might have pulled, merged and forked my past "messy" commits, thus finding himself out of synch.
Anyhow, I'll just have to sit a whole day with a boring book to solve the mistery.
;-)

**Comment by tsjensen** [comment]
Thanks, merged!
(Btw, the force push is ok on your feature branch; we just wouldn't want it in the main repo.)

**Pull request merged**
