### PR TITLE
Add a simle square box

### PR DESCRIPTION
**Pull request by jensim**
```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Using utf-8 characters to draw a square. ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

### CODE REVIEW

**Comment by tsjensen** [comment]
The boxes config file is currently ASCII-encoded, so it can't handle multi-byte characters.
Admittedly, there are some scenarios where it might work (on your machine), like when you configure your terminal to run on iso-8859-15 because that's single-byte. But I still can't merge it because it wouldn't work for most people.

On my machine, it looks like this (top: as multi-byte UTF-8, bottom: as iso-8859-15): 
image

Sorry about that! I will come back to it when, some time in the future, we support multi-byte config files. Until then, consider the `stone` design:
```
+-------------------+
| I am square, too. |
+-------------------+
```

**Comment by jensim** [comment]
Thats a shame 
But thank you fpr the fast feedback on this

It gave me a punny idea, to write a RustImplementation of this called BoxeRS 🥳
Maybe with full UTF8 and emoji support 😃🏴‍☠️💡🤭

**Comment by nnuel** [comment]
Ah, I just see the same problem here, I already suspected it had to do something with ASCII vs. extended ASCII characters.

@jensim How difficult do you think it would be to created something for simple box lines or using these characters: ██
I'd be curious to know if you ever gave it a go

**Comment by jensim** [comment]
I never gave it a go, my cost benefit analysis came out to low  😅🤷

**Pull request closed without merging**
